### ISSUE TITLE
TKperf crash on raid test

### ISSUE THREAD

**Issue by kbeyer33** [thomas-krenn/TKperf#41]
If I start TKperf 2.2 on Debian 11 (bullseye) with python 3.9.2 for a raid0 of NVME devices, it crashes with:
root@debian:~# tkperf raid NVME_raid0 /dev/md0 -c raid0.cfg -nj 2 -iod 16
Traceback (most recent call last):
  File "/usr/local/bin/tkperf", line 110, in <module>
    myTest.initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/PerfTest.py", line 161, in initialize
    v.initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/DeviceTests.py", line 69, in initialize
    self.getDevice().initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/Devices.py", line 820, in initialize
    self.__raidTec.createVD()
  File "/usr/local/lib/python3.9/dist-packages/system/OS.py", line 115, in createVD
    logging.error("mdadm encountered an error: " + stderr)
TypeError: can only concatenate str (not "bytes") to str

raid0.cfg is:
[raid0.cfg.txt](https://github.com/thomas-krenn/TKperf/files/7337684/raid0.cfg.txt)

The logfile shows:
20211013 11:57 root     INFO     # Initialiazing test iops
20211013 11:57 root     INFO     # Checking for device /dev/md0
20211013 11:57 root     INFO     # Creating raid device /dev/md0
20211013 11:57 root     INFO     # Command line: /usr/sbin/mdadm --create /dev/md0 --quiet --metadata=default --level=0 --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1

If I run the command "/usr/sbin/mdadm --create /dev/md0 --quiet --metadata=default --level=0 --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1" manually, it succeeds without error.

**Comment by kbeyer33** [comment]
Commit 638b083 fixed this issue. Thank you Georg.
