### ISSUE TITLE
TKperf crash with UnicodeDecodeError

### ISSUE THREAD

**Issue by kbeyer33** [thomas-krenn/TKperf#42]
Some NVME devices return invalid bytes in output of command "nvme id-ctrl <device>". This causes a crash on Debian 11 (bullseye) with Python 3.9.2:
root@debian:~# tkperf ssd NVME /dev/nvme1n1 -nj 2 -iod 16 -rfb -i nvme
Traceback (most recent call last):
  File "/usr/local/bin/tkperf", line 110, in <module>
    myTest.initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/PerfTest.py", line 161, in initialize
    v.initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/DeviceTests.py", line 69, in initialize
    self.getDevice().initialize()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/Devices.py", line 103, in initialize
    self.readDevInfo()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/Devices.py", line 483, in readDevInfo
    super(SSD, self).readDevInfo()
  File "/usr/local/lib/python3.9/dist-packages/perfTest/Devices.py", line 410, in readDevInfo
    (stdout,stderr) = out.communicate()
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 2019, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.9/subprocess.py", line 1011, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 364: invalid start byte

The output of the command is attached
[id-ctrl_nvme1n1.txt](https://github.com/thomas-krenn/TKperf/files/7337759/id-ctrl_nvme1n1.txt)
.

**Comment by kbeyer33** [comment]
Commit 56f5709 fixed this issue.

**Comment by gschoenberger** [comment]
This is still open as I have to fix the utf-8 decode error when parsing the device information...work in progress, hope to fix it soon

**Comment by jackeichen** [comment]
I have ever got the issue in other scripts, usually because the deocde type. I think it can be solved like this:

```
for encode_t in ("UTF-8", "GBK", "GB2312"):
    try:
        out = subprocess.Popen(['sginfo', '-a', self.__path],stdout=subprocess.PIPE,stderr=subprocess.PIPE,universal_newlines=True, encoding=encode_t)
        (stdout,stderr) = out.communicate()
    except UnicodeDecodeError:
        pass
    else:
        break
```

Hope this will be helpful!
